### ISSUE TITLE
Updating to ember 2.7 causes problems with item/optionComponent usage

### ISSUE THREAD

**Issue by timmorey** [miguelcobain/ember-cli-selectize#159]
I recently updated a project to ember 2.7, and found that this broke my usage of the `ember-selectize` component.  I've been supplying the `itemComponent` and `optionComponent` properties to specify which component should provide the content for the selectize control.  After updating, I get `ember-selectize.js:819 Uncaught TypeError: componentLookup.lookupFactory is not a function` when trying to render the selectize component.

Further error detail:

![screen shot 2016-08-01 at 4 14 34 pm](https://cloud.githubusercontent.com/assets/2340894/17307429/160b28be-5803-11e6-871a-31a3fcd314bd.png)

I created the simplest repro case I could come up with to help narrow down the problem: https://github.com/timmorey/selectize-regression.  The app just tries to display a selectize component with custom content.  All tests pass and everything works fine at ember 2.6 (https://github.com/timmorey/selectize-regression/commit/73427761ea8c6f5c5f4bee3fbc8eded00176ae37), but the selectize stops working and tests fail after updating to 2.7 (https://github.com/timmorey/selectize-regression/commit/ce653d0558b399448991d92ff8af18c164c42962)

Any idea what is going wrong here?

**Comment by safeforge** [comment]
@timmorey can you test with my fork?

```
 "ember-cli-selectize": "safeforge/ember-cli-selectize",
```

**Comment by timmorey** [comment]
@safeforge I tried that branch, and it fixes my test case.  Also tried it in my real app, and it seems to work.

**Comment by IAmJulianAcosta** [comment]
Works only in 2.7 but not in 2.8.

`component.createElement()` is not a function

**Comment by miguelcobain** [comment]
Can someone try with 0.5.6 and close if it works?

**Comment by gogromat** [comment]
It would not work with ```0.5.12```, since it has that ```_lookupFactory``` call.
On development the error would state:
```DEPRECATION: Using "_lookupFactory" is deprecated. Please use container.factoryFor instead. [deprecation id: container-lookupFactory] See http://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor for more details.```
